name: ehr
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  # State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  
  # Database
  sqflite: ^2.3.3+1
  path: ^1.9.0
  
  # Navigation
  go_router: ^14.2.7
  
  # UI Components
  flutter_form_builder: ^9.2.1
  form_builder_validators: ^11.1.2
  
  # Date & Time
  intl: ^0.19.0
  
  # JSON Handling
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  # Code Generation
  riverpod_generator: ^2.4.3
  build_runner: ^2.4.12
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
